version: 2
registries:
  npm-registry-npm-pkg-github-com-goproperly:
    type: npm-registry
    url: https://npm.pkg.github.com/goproperly
    token: "${{secrets.PROPERLY_GITHUB_REPO_ACCESS}}"
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.PROPERLY_GITHUB_REPO_ACCESS}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.4.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: commitizen
    versions:
    - 4.2.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  registries:
  - npm-registry-npm-pkg-github-com-goproperly
  - npm-registry-npm-pkg-github-com
